version: '3'

services:
  database:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - inet

  cache:
    restart: always
    image: redis
    expose:
      - 6379
    networks:
      - inet

  email:
    restart: always
    build:
      context: ./email
    networks:
      - inet

  app:
    restart: always
    build:
      context: ./app
    networks:
      - inet
    depends_on:
      - database
      - cache
      - email

  webserver:
    restart: always
    build:
      context: ./webserver
    volumes:
      - ./webserver/static:/vol/static/
      - certbot:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - inet
    depends_on:
      - app

networks:
  inet:

volumes:
  db-data:
  static:
  certbot: