version: '3'

services:
  database:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - inet

  cache:
    restart: always
    image: redis
    expose:
      - 6379
    networks:
      - inet

  email:
    restart: always
    build:
      context: ./email
    networks:
      - inet

  # backend:
  #   restart: always
  #   build:
  #     context: ./backend
  #   volumes:
  #     - ./webserver/static:/vol/static/
  #   networks:
  #     - inet
  #   depends_on:
  #     - database
  #     - cache
  #     - email

  frontend:
    restart: always
    build:
      context: ./frontend
    networks:
      - inet
    # depends_on:
    #   - backend

  webserver:
    restart: always
    build:
      context: ./webserver
    volumes:
      - ./webserver/static:/vol/static/
      - certbot:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - inet
    depends_on:
      # - backend
      - frontend

networks:
  inet:

volumes:
  db-data:
  static:
  certbot: