export default {
    "Inicio": "Home",
    "Catálogo": "Catalog",
    "Procurar": "Search",
    "Login": "Login",
    "Contatos": "Contacts",
    "Informação": "Information",
    "Website em desenvolvimento por:": "Website in development by:",
    "Ajuda": "Help",
    "Precisa de ajuda?": "Need help?",
    "Entre em contato com os administradores do sistema.": "Contact the system administrators.",
    "Página Principal": "Home",
    "Especializada em trade itens de DOTA 2.": "Specialized in trading DOTA 2 items.",
    "Melhor preço sempre." : "Best price always.",
    "Usuário": "User",
    "Senha": "Password",
    "Login com Steam": "Login with Steam",
    "Login com Google": "Login with Google",
    "Aviso": "Warning",
    "Essa funcionalidade ainda não foi implementada." : "This feature has not been implemented yet.",
    "Destaques": "Highlights",
    "Heróis": "Heroes",
    "Raridade": "Rarity",
    "Selecionar": "Select",
    "Loja": "Store",
    "R$": "$",
    "Selecione os Heróis que deseja filtrar:" : "Select the Heroes you want to filter:",
    "Confirmar": "Confirm",
    "Cancelar": "Cancel",
    "Carrinho": "Cart",
    "Itens:": "Items:",
    "Subtotal:": "Subtotal:",
    "Finalizar Compra": "Checkout",
    "Voltar às compras": "Back to shopping",
}